#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | www.openfoam.com
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
#     Copyright (C) 2019-2021 OpenCFD Ltd.
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
#
# Script
#     makeFlex
#
# Description
#     Build the Flex libraries, optionally build binaries
#
# ----------------------------------------------
# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
#------------------------------------------------------------------------------
# Short-circuit test for an installation
if [ "$1" = "-test" ]
then
    [ "$#" -eq 2 ] || { echo "${0##*/} -test : needs 1 argument"; exit 1; }
    dir="${2%/}" # <- *_ARCH_PATH
    [ -d "$dir/include" ] || exit 2

    package="flex"
    if [ -d "$dir/include" ]; then
      echo "    $package include: $dir/include"
      exit 0
    fi
    exit 2
fi
#------------------------------------------------------------------------------
if :; then # Run from third-party directory
  cd "${0%/*}" || exit
  wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
  }
fi
. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
#------------------------------------------------------------------------------
_foamConfig flex # Get FLEX_ARCH_PATH, FLEX_VERSION

PACKAGE="${FLEX_VERSION:-system}"

if nonStandardPlatforms; then # Possibly unreliable inherited values
  unset FLEX_ARCH_PATH
fi

#------------------------------------------------------------------------------
printVersions() {
  listPackageVersions flex
  exit 0
}
printHelp() {
  /bin/cat <<USAGE

Usage: ${0##*/} [OPTION] [libso] [FLEX-VERSION]
options:
  -force        Force compilation, even if include/library already exists
                Also force build attempt of flex
  -gcc          Force use of gcc/g++
  -toolchain PATH   Specify toolchain file 
  -list         List available unpacked source versions
  -help         Display usage help

* Build FLEX
      ${PACKAGE:-[unspecified]}

USAGE
  showDownloadHint flex
  exit 0 # Clean exit
}
#------------------------------------------------------------------------------

unset optForce optNoExtlib
optBinaries=false
optLabelSize="${WM_LABEL_SIZE:-32}"

# Parse options
while [ "$#" -gt 0 ]; do
  case "$1" in
  '') ;; # Ignore empty
  -h | -help*) printHelp ;;
  -list) printVersions ;;
  -force) optForce=true ;;
  -bin) optBinaries=true ;;
  -no-bin) optBinaries=false ;;

  flex/ | sources/flex* | \
    flex-[0-9]* | flex-v[0-9]* | flex-git | flex_*)
    PACKAGE="${1%%/}"
    unset FLEX_ARCH_PATH # Avoid inconsistency
    ;;
  *)
    die "unknown option/argument: '$1'"
    ;;
  esac
  shift
done

if [ -z "$PACKAGE" ]; then
  die "The flex package/version not specified"
elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"; then
  echo "Using none/system (skip ThirdParty build of flex)"
  exit 0
fi

if [ "$optNoExtlib" = true ]; then
  unset FOAM_EXT_LIBBIN
else
  requireExtLibBin
fi

#------------------------------------------------------------------------------
#
# Build flex
#   FLEX_ARCH_PATH : installation directory (as per config file)
#
#   *PACKAGE : name-version of the package
#   *SOURCE  : location of original sources
#   *PREFIX  : installation directory

PKG_SOURCE="$(findSourceDir "$PACKAGE")"
PACKAGE="$(basename "$PACKAGE")"
PKG_PREFIX="$installBASE/$PACKAGE"
export GIT_DIR="$PKG_SOURCE/.git"

# Override as per config file (if any)
[ -n "$FLEX_ARCH_PATH" ] && PKG_PREFIX="$FLEX_ARCH_PATH"

[ -d "$PKG_SOURCE" ] || {
  echo "Missing sources: '$PACKAGE'"
  showDownloadHint flex
  exit 2
}

#------------------------------------------------------------------------------

# Use make for the flex build

if [ -z "$optForce" ] \
&& {
	  [ -r "$PKG_PREFIX/include/FlexLexer.h" ] \
	&& [ -r "$PKG_PREFIX/lib/libfl$EXT_SO" ] 

} ; then
  echo "Already built: $PACKAGE"
else
  echo "Starting build: $PACKAGE"
  (
	
	PKG_BUILD="$buildBASE/$PACKAGE"
    cd "$PKG_SOURCE" || exit

	rm -rf "$PKG_PREFIX"
	rm -rf "$PKG_BUILD"
	mkdir -p "$PKG_BUILD"

    cd "$PKG_BUILD" && set -x  \
	&& "$PKG_SOURCE"/configure --prefix=$PKG_PREFIX \
	&& set +x \
    && make -j $WM_NCOMPPROCS \
	&& make install \
    && echo "Built: $PACKAGE"
  ) || {
    echo "Error building: $PACKAGE"
    exit 1
  }
fi

#------------------------------------------------------------------------------
