#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | www.openfoam.com
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
#     Copyright (C) 2011 OpenFOAM Foundation
#     Copyright (C) 2016-2021 OpenCFD Ltd.
#------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM, distributed under GPL-3.0-or-later.
#
# Script
#     makeCKIII
#
# Description
#     Build script for CKIII.
#
# ----------------------------------------------
# NO USER-CONFIGURABLE SETTINGS WITHIN THIS FILE
#------------------------------------------------------------------------------
# Short-circuit test for an installation
if [ "$1" = "-test" ]; then
  [ "$#" -eq 2 ] || {
    echo "${0##*/} -test : needs 1 argument"
    exit 1
  }
  dir="${2%/}" # <- *_ARCH_PATH

  package="ckiii"
  libName="libck"
  for lib in \
    "$dir/lib/$libName.a" \
    "$dir/lib$WM_COMPILER_LIB_ARCH/$libName.a"; do
    if [ -r "$lib" ]; then
      echo "    $package library: ${lib%/*}"
      exit 0
    fi
  done
  exit 2
fi
#------------------------------------------------------------------------------
if :; then # Run from third-party directory
  cd "${0%/*}" || exit
  wmakeCheckPwd "$WM_THIRD_PARTY_DIR" 2>/dev/null || {
    echo "Error (${0##*/}) : not located in \$WM_THIRD_PARTY_DIR"
    echo "    Check your OpenFOAM environment and installation"
    exit 1
  }
fi
. "${WM_THIRD_PARTY_DIR:?}"/etc/tools/ThirdPartyFunctions
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Obtain version from OpenFOAM etc/config.sh file:
_foamConfig ckiii

PACKAGE="${CKIII_VERSION:-system}"

#------------------------------------------------------------------------------
printVersions() {
  listPackageVersions ckiii
  exit 0
}
printHelp() {
  cat <<USAGE

Usage: ${0##*/} [OPTION] ckiii-VERSION
options:
  -force        Force compilation, even if binary already exists
  -gcc          Force use of gcc/g++
  -list         List available unpacked source versions
  -help         Display usage help

* Build CKIII
      ${PACKAGE:-[unspecified]}

USAGE
  showDownloadHint ckiii
  exit 0 # Clean exit
}
#------------------------------------------------------------------------------
exportCompiler # Compiler info for CKIII/configure

unset optForce

# Parse options
while [ "$#" -gt 0 ]; do
  case "$1" in
  '') ;; # Ignore empty
  -h | -help*) printHelp ;;
  -list) printVersions ;;
  -gcc) useGcc ;;
  -force) optForce=true ;;

  libck/* | libck/* | \
    sources/libck-* | sources/libck-* | \
    libck-[0-9]* | libck-[0-9]*)
    PACKAGE="${1%%/}"
    ;;
  *)
    die "unknown option/argument: '$1'"
    ;;
  esac
  shift
done

if [ -z "$PACKAGE" ]; then
  die "The CKIII package/version not specified"
elif _foamIsNone "$PACKAGE" || _foamIsSystem "$PACKAGE"; then
  echo "Using none/system (skip ThirdParty build of CKIII)"
  exit 0
fi

#------------------------------------------------------------------------------
#
# Build CKIII
#   *PACKAGE : name-version of the package
#   *SOURCE  : location of original sources
#   *PREFIX  : installation directory

PKG_SOURCE="$(findSourceDir "$PACKAGE")"
PACKAGE="$(basename "$PACKAGE")"
PKG_PREFIX="$installBASE/$PACKAGE"
export GIT_DIR="$PKG_SOURCE/.git"

# Override as per config file (if any)
[ -n "$CKIII_ARCH_PATH" ] && PKG_PREFIX="$CKIII_ARCH_PATH"
[ -r "$PKG_SOURCE/cklib.f" ] || {
  echo "Missing sources: '$PACKAGE'"
  showDownloadHint ckiii
  exit 2
}

if [ -z "$optForce" ] &&
  {
    [ -r "$PKG_PREFIX/lib/libck$EXT_SO" ] ||
      [ -r "$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH/libck$EXT_SO" ]
  }; then
  echo "Already has shared library: $PKG_PREFIX"
elif [ -z "$optForce" ] &&
  {
    [ -r "$PKG_PREFIX/lib/libck.a" ] ||
      [ -r "$PKG_PREFIX/lib$WM_COMPILER_LIB_ARCH/libck.a" ]
  }; then
  echo "Already has static library: $PKG_PREFIX"
else
  echo "Starting build: $PACKAGE"
  (
    PKG_BUILD="$buildBASE/$PACKAGE"
    cd "$PKG_SOURCE" || exit
    make distclean 2>/dev/null || true

    rm -rf "$PKG_BUILD"
    mkdir -p "$PKG_BUILD"

    unset buildOpt
    if [ "$WM_ARCH" = linuxSW64 ]; then
      buildOpt="-DCMAKE_Fortran_COMPILER=swgfortran"
    fi

    cmake=$(findCMake)

    cd "$PKG_BUILD" && set -x &&
      ${cmake:?} \
        -B "$PKG_BUILD" \
        -S "$PKG_SOURCE" \
        -DCMAKE_INSTALL_PREFIX="$PKG_PREFIX" \
        -DCMAKE_BUILD_TYPE=Release \
        $buildOpt &&
      set +x &&
      time make -j $WM_NCOMPPROCS &&
      make install &&
      echo "Built: $PACKAGE"
  ) || {
    echo "Error building: $PACKAGE"
    exit 1
  }
fi

#------------------------------------------------------------------------------
